import { PixelRatio } from 'react-native';
import type { ImageSource } from 'expo-image';
import type { CardDefinition } from '../types/hwatu';

type Density = '1x' | '2x' | '3x';

function getDensity(): Density {
  const scale = PixelRatio.get();
  if (scale >= 3) return '3x';
  if (scale >= 2) return '2x';
  return '1x';
}

const IMAGES_1X: Record<string, ImageSource> = {
  'apr-animal': require('../../assets/cards/1x/apr-animal.png'),
  'apr-junk-1': require('../../assets/cards/1x/apr-junk-1.png'),
  'apr-junk-2': require('../../assets/cards/1x/apr-junk-2.png'),
  'apr-ribbon': require('../../assets/cards/1x/apr-ribbon.png'),
  'aug-animal': require('../../assets/cards/1x/aug-animal.png'),
  'aug-bright': require('../../assets/cards/1x/aug-bright.png'),
  'aug-junk-1': require('../../assets/cards/1x/aug-junk-1.png'),
  'aug-ribbon': require('../../assets/cards/1x/aug-ribbon.png'),
  'dec-junk-1': require('../../assets/cards/1x/dec-animal.png'),
  'dec-junk-2': require('../../assets/cards/1x/dec-ribbon.png'),
  'dec-junk-double': require('../../assets/cards/1x/dec-junk-double.png'),
  'dec-rain': require('../../assets/cards/1x/dec-rain.png'),
  'feb-animal': require('../../assets/cards/1x/feb-animal.png'),
  'feb-junk-1': require('../../assets/cards/1x/feb-junk-1.png'),
  'feb-junk-2': require('../../assets/cards/1x/feb-junk-2.png'),
  'feb-ribbon': require('../../assets/cards/1x/feb-ribbon.png'),
  'jan-bright': require('../../assets/cards/1x/jan-bright.png'),
  'jan-junk-1': require('../../assets/cards/1x/jan-junk-1.png'),
  'jan-junk-2': require('../../assets/cards/1x/jan-junk-2.png'),
  'jan-ribbon': require('../../assets/cards/1x/jan-ribbon.png'),
  'jul-animal': require('../../assets/cards/1x/jul-animal.png'),
  'jul-junk-1': require('../../assets/cards/1x/jul-junk-1.png'),
  'jul-junk-2': require('../../assets/cards/1x/jul-junk-2.png'),
  'jul-ribbon': require('../../assets/cards/1x/jul-ribbon.png'),
  'jun-animal': require('../../assets/cards/1x/jun-animal.png'),
  'jun-junk-1': require('../../assets/cards/1x/jun-junk-1.png'),
  'jun-junk-2': require('../../assets/cards/1x/jun-junk-2.png'),
  'jun-ribbon': require('../../assets/cards/1x/jun-ribbon.png'),
  'mar-bright': require('../../assets/cards/1x/mar-bright.png'),
  'mar-junk-1': require('../../assets/cards/1x/mar-junk-1.png'),
  'mar-junk-2': require('../../assets/cards/1x/mar-junk-2.png'),
  'mar-ribbon': require('../../assets/cards/1x/mar-ribbon.png'),
  'may-animal': require('../../assets/cards/1x/may-animal.png'),
  'may-junk-1': require('../../assets/cards/1x/may-junk-1.png'),
  'may-junk-2': require('../../assets/cards/1x/may-junk-2.png'),
  'may-ribbon': require('../../assets/cards/1x/may-ribbon.png'),
  'nov-animal': require('../../assets/cards/1x/nov-animal.png'),
  'nov-junk-1': require('../../assets/cards/1x/nov-junk-1.png'),
  'nov-junk-2': require('../../assets/cards/1x/nov-junk-2.png'),
  'nov-junk-double': require('../../assets/cards/1x/nov-junk-double.png'),
  'oct-animal': require('../../assets/cards/1x/oct-animal.png'),
  'oct-junk-1': require('../../assets/cards/1x/oct-junk-1.png'),
  'oct-junk-2': require('../../assets/cards/1x/oct-junk-2.png'),
  'oct-junk-3': require('../../assets/cards/1x/oct-ribbon.png'),
  'sep-animal-double': require('../../assets/cards/1x/sep-junk-double.png'),
  'sep-junk-1': require('../../assets/cards/1x/sep-junk-1.png'),
  'sep-junk-2': require('../../assets/cards/1x/sep-junk-2.png'),
  'sep-ribbon': require('../../assets/cards/1x/sep-ribbon.png'),
};

const IMAGES_2X: Record<string, ImageSource> = {
  'apr-animal': require('../../assets/cards/2x/apr-animal.png'),
  'apr-junk-1': require('../../assets/cards/2x/apr-junk-1.png'),
  'apr-junk-2': require('../../assets/cards/2x/apr-junk-2.png'),
  'apr-ribbon': require('../../assets/cards/2x/apr-ribbon.png'),
  'aug-animal': require('../../assets/cards/2x/aug-animal.png'),
  'aug-bright': require('../../assets/cards/2x/aug-bright.png'),
  'aug-junk-1': require('../../assets/cards/2x/aug-junk-1.png'),
  'aug-ribbon': require('../../assets/cards/2x/aug-ribbon.png'),
  'dec-junk-1': require('../../assets/cards/2x/dec-animal.png'),
  'dec-junk-2': require('../../assets/cards/2x/dec-ribbon.png'),
  'dec-junk-double': require('../../assets/cards/2x/dec-junk-double.png'),
  'dec-rain': require('../../assets/cards/2x/dec-rain.png'),
  'feb-animal': require('../../assets/cards/2x/feb-animal.png'),
  'feb-junk-1': require('../../assets/cards/2x/feb-junk-1.png'),
  'feb-junk-2': require('../../assets/cards/2x/feb-junk-2.png'),
  'feb-ribbon': require('../../assets/cards/2x/feb-ribbon.png'),
  'jan-bright': require('../../assets/cards/2x/jan-bright.png'),
  'jan-junk-1': require('../../assets/cards/2x/jan-junk-1.png'),
  'jan-junk-2': require('../../assets/cards/2x/jan-junk-2.png'),
  'jan-ribbon': require('../../assets/cards/2x/jan-ribbon.png'),
  'jul-animal': require('../../assets/cards/2x/jul-animal.png'),
  'jul-junk-1': require('../../assets/cards/2x/jul-junk-1.png'),
  'jul-junk-2': require('../../assets/cards/2x/jul-junk-2.png'),
  'jul-ribbon': require('../../assets/cards/2x/jul-ribbon.png'),
  'jun-animal': require('../../assets/cards/2x/jun-animal.png'),
  'jun-junk-1': require('../../assets/cards/2x/jun-junk-1.png'),
  'jun-junk-2': require('../../assets/cards/2x/jun-junk-2.png'),
  'jun-ribbon': require('../../assets/cards/2x/jun-ribbon.png'),
  'mar-bright': require('../../assets/cards/2x/mar-bright.png'),
  'mar-junk-1': require('../../assets/cards/2x/mar-junk-1.png'),
  'mar-junk-2': require('../../assets/cards/2x/mar-junk-2.png'),
  'mar-ribbon': require('../../assets/cards/2x/mar-ribbon.png'),
  'may-animal': require('../../assets/cards/2x/may-animal.png'),
  'may-junk-1': require('../../assets/cards/2x/may-junk-1.png'),
  'may-junk-2': require('../../assets/cards/2x/may-junk-2.png'),
  'may-ribbon': require('../../assets/cards/2x/may-ribbon.png'),
  'nov-animal': require('../../assets/cards/2x/nov-animal.png'),
  'nov-junk-1': require('../../assets/cards/2x/nov-junk-1.png'),
  'nov-junk-2': require('../../assets/cards/2x/nov-junk-2.png'),
  'nov-junk-double': require('../../assets/cards/2x/nov-junk-double.png'),
  'oct-animal': require('../../assets/cards/2x/oct-animal.png'),
  'oct-junk-1': require('../../assets/cards/2x/oct-junk-1.png'),
  'oct-junk-2': require('../../assets/cards/2x/oct-junk-2.png'),
  'oct-junk-3': require('../../assets/cards/2x/oct-ribbon.png'),
  'sep-animal-double': require('../../assets/cards/2x/sep-junk-double.png'),
  'sep-junk-1': require('../../assets/cards/2x/sep-junk-1.png'),
  'sep-junk-2': require('../../assets/cards/2x/sep-junk-2.png'),
  'sep-ribbon': require('../../assets/cards/2x/sep-ribbon.png'),
};

const IMAGES_3X: Record<string, ImageSource> = {
  'apr-animal': require('../../assets/cards/3x/apr-animal.png'),
  'apr-junk-1': require('../../assets/cards/3x/apr-junk-1.png'),
  'apr-junk-2': require('../../assets/cards/3x/apr-junk-2.png'),
  'apr-ribbon': require('../../assets/cards/3x/apr-ribbon.png'),
  'aug-animal': require('../../assets/cards/3x/aug-animal.png'),
  'aug-bright': require('../../assets/cards/3x/aug-bright.png'),
  'aug-junk-1': require('../../assets/cards/3x/aug-junk-1.png'),
  'aug-ribbon': require('../../assets/cards/3x/aug-ribbon.png'),
  'dec-junk-1': require('../../assets/cards/3x/dec-animal.png'),
  'dec-junk-2': require('../../assets/cards/3x/dec-ribbon.png'),
  'dec-junk-double': require('../../assets/cards/3x/dec-junk-double.png'),
  'dec-rain': require('../../assets/cards/3x/dec-rain.png'),
  'feb-animal': require('../../assets/cards/3x/feb-animal.png'),
  'feb-junk-1': require('../../assets/cards/3x/feb-junk-1.png'),
  'feb-junk-2': require('../../assets/cards/3x/feb-junk-2.png'),
  'feb-ribbon': require('../../assets/cards/3x/feb-ribbon.png'),
  'jan-bright': require('../../assets/cards/3x/jan-bright.png'),
  'jan-junk-1': require('../../assets/cards/3x/jan-junk-1.png'),
  'jan-junk-2': require('../../assets/cards/3x/jan-junk-2.png'),
  'jan-ribbon': require('../../assets/cards/3x/jan-ribbon.png'),
  'jul-animal': require('../../assets/cards/3x/jul-animal.png'),
  'jul-junk-1': require('../../assets/cards/3x/jul-junk-1.png'),
  'jul-junk-2': require('../../assets/cards/3x/jul-junk-2.png'),
  'jul-ribbon': require('../../assets/cards/3x/jul-ribbon.png'),
  'jun-animal': require('../../assets/cards/3x/jun-animal.png'),
  'jun-junk-1': require('../../assets/cards/3x/jun-junk-1.png'),
  'jun-junk-2': require('../../assets/cards/3x/jun-junk-2.png'),
  'jun-ribbon': require('../../assets/cards/3x/jun-ribbon.png'),
  'mar-bright': require('../../assets/cards/3x/mar-bright.png'),
  'mar-junk-1': require('../../assets/cards/3x/mar-junk-1.png'),
  'mar-junk-2': require('../../assets/cards/3x/mar-junk-2.png'),
  'mar-ribbon': require('../../assets/cards/3x/mar-ribbon.png'),
  'may-animal': require('../../assets/cards/3x/may-animal.png'),
  'may-junk-1': require('../../assets/cards/3x/may-junk-1.png'),
  'may-junk-2': require('../../assets/cards/3x/may-junk-2.png'),
  'may-ribbon': require('../../assets/cards/3x/may-ribbon.png'),
  'nov-animal': require('../../assets/cards/3x/nov-animal.png'),
  'nov-junk-1': require('../../assets/cards/3x/nov-junk-1.png'),
  'nov-junk-2': require('../../assets/cards/3x/nov-junk-2.png'),
  'nov-junk-double': require('../../assets/cards/3x/nov-junk-double.png'),
  'oct-animal': require('../../assets/cards/3x/oct-animal.png'),
  'oct-junk-1': require('../../assets/cards/3x/oct-junk-1.png'),
  'oct-junk-2': require('../../assets/cards/3x/oct-junk-2.png'),
  'oct-junk-3': require('../../assets/cards/3x/oct-ribbon.png'),
  'sep-animal-double': require('../../assets/cards/3x/sep-junk-double.png'),
  'sep-junk-1': require('../../assets/cards/3x/sep-junk-1.png'),
  'sep-junk-2': require('../../assets/cards/3x/sep-junk-2.png'),
  'sep-ribbon': require('../../assets/cards/3x/sep-ribbon.png'),
};

const IMAGE_MAPS: Record<Density, Record<string, ImageSource>> = {
  '1x': IMAGES_1X,
  '2x': IMAGES_2X,
  '3x': IMAGES_3X,
};

export function getCardImageSource(card: CardDefinition): ImageSource {
  return IMAGE_MAPS[getDensity()][card.id];
}

export function getCardBackSource(): ImageSource {
  // Metro resolves @2x/@3x variants from the base filename — don't require them directly
  return require('../../assets/cards/back/card-back.png');
}
